### ISSUE TITLE
`WindowSettings` should have a `maximized` option too

### ISSUE THREAD

**Issue by dlight** [hecrj/coffee#105]
Actually, I will make a PR. But `WindowSettings` should probably implement `Default` and/or a builder pattern as well, so that people don't need to specify all options if they want to adjust just some.

**Comment by dlight** [comment]
There's a lot of other api surface that winit exposes that could be useful to expose in coffee, too.

**Comment by hecrj** [comment]
I think we can keep `WindowSettings` explicit for now. In most cases, users only have to write it once.

Closed via #106.
