### ISSUE TITLE
Draw an `Image` with nearest-neighbor interpolation

### ISSUE THREAD

**Issue by dlight** [hecrj/coffee#110]
Hello, is there any way to draw a texture with nearest-neighbor interpolation? Like `GL_NEAREST` or ggez's [`FilterMode::Nearest`](https://docs.rs/ggez/0.5.1/ggez/graphics/enum.FilterMode.html#variant.Nearest).

(right now, instead of drawing the image I issue multiple draw commands, one rect for each pixel)

**Comment by hecrj** [comment]
Nearest neighbor interpolation is the only supported filtering mode as of now (#9).

**Comment by dlight** [comment]
Oops, you're right. When I tested it, my colors were too close to each other to see it pixelated. 😅
