### ISSUE TITLE
error: could not compile `matrixmultiply`.

### ISSUE THREAD

**Issue by WhatWithCheeze432** [hecrj/coffee#118]
**Log**:

- http://paste.debian.net/1126708/

________________________

**Description**: The log states it all, basically `cargo` won't properly load the coffee/dependencies, or at least on my setup. 

**Cargo Version**: `cargo 1.42.0-nightly (6e1ca924a 2020-01-06)`
**OS**: Debian GNU/Linux

**Comment by hecrj** [comment]
This is a compiler bug affecting `nightly`: https://github.com/rust-lang/rust/issues/67743
