### ISSUE TITLE
error: failed to run custom build command for `libudev-sys v0.1.4`

### ISSUE THREAD

**Issue by WhatWithCheeze432** [hecrj/coffee#119]
**Log**:

- http://paste.debian.net/1126913

________________________

**Description**: The log states it all, basically `cargo` won't properly load the coffee/dependencies, or at least on my setup. 

**Cargo Version**: `cargo 1.40.0 (bc8e4c8be 2019-11-22)`
**OS**: Debian GNU/Linux

**Comment by hecrj** [comment]
As per the error message, you are missing `libudev`. Installing the `libudev-dev` package should fix the issue.

**Comment by djhunter67** [comment]
I am on Arch linux and I have the same error.  There is no `libudev-dev` for Arch in any of the `yay` repos. I have been troubleshooting for hours.  The solution for openssl was `export OPENSSL_INCLUDE_DIR=/usr/include` and `export OPENSSL_DIR=/usr/`
