### ISSUE TITLE
Coffee + specs

### ISSUE THREAD

**Issue by twe4ked** [hecrj/coffee#70]
Hello! I'm having some trouble with borrowing when integrating Coffee and specs. The Coffee interact function borrows `&mut State` which is where I'm storing my specs `World`. When I try to run a specs System on the `World` it blows up with a alloc::boxed::Box<dyn shred::world::Resource> already borrowed mutably error. Is there a way I can make this work? Is there any prior art for coffee + specs?

I'm re-posting here so I don't lose it in the Discord again!

Your response:

> You shouldn't need to do anything special to get specs to work with Coffee. Simply store it in your type implementing Game, and you should be able to access it normally from interact and update.
> – @hecrj

I'm storing the `World` on my type implementing `Game` as suggested which is where I believe the borrow error is coming from.

_a few days later_

After you said it should just work I took another crack and worked it out. Here's the code with the fix in case it helps other folks. The problematic code and fix is in the `interact` function.

```rust
use coffee::{
    graphics::{Color, Frame, Window, WindowSettings},
    load::Task,
    Game, Result, Timer,
};
use specs::{prelude::*, Builder, Component, VecStorage, World, Write, WriteStorage};

#[macro_use]
extern crate specs_derive;

#[derive(Component, Debug)]
#[storage(VecStorage)]
pub struct Foo;

#[derive(Component, Debug, Default)]
#[storage(VecStorage)]
pub struct Bar {
    baz: f32,
}

pub struct System;

impl<'a> specs::System<'a> for System {
    type SystemData = (WriteStorage<'a, Foo>, Write<'a, Bar>);

    fn run(&mut self, (_, _): Self::SystemData) {
        //
    }
}

struct State {
    world: World,
}

impl Game for State {
    type Input = ();
    type LoadingScreen = ();

    fn load(_window: &Window) -> Task<Self> {
        Task::new(move || {
            let mut world = World::new();
            world.register::<Foo>();
            world.insert(Bar { baz: 42.0 });
            world.create_entity().with(Foo {}).build();

            State { world }
        })
    }

    fn interact(&mut self, _input: &mut (), _window: &mut Window) {
        // Breaks:
        let mut bar = self.world.write_resource::<Bar>();
        *bar = Bar { baz: 43.0 };

        // Fixed:
        // {
        //     let mut bar = self.world.write_resource::<Bar>();
        //     *bar = Bar { baz: 43.0 };
        // }

        let mut system = System;
        system.run_now(&self.world);
    }

    fn draw(&mut self, frame: &mut Frame, _timer: &Timer) {
        frame.clear(Color::BLACK);
    }
}

fn main() -> Result<()> {
    State::run(WindowSettings {
        title: String::from("Foo"),
        size: (1280, 1024),
        resizable: true,
        fullscreen: false,
    })
}
```

Thanks!

**Comment by hecrj** [comment]
Thank your for documenting this!

Just to clarify further:

```rust
let mut bar = self.world.write_resource::<Bar>();
*bar = Bar { baz: 43.0 };

let mut system = System;
system.run_now(&self.world);
```

The issue here is that `bar` keeps the `Bar` resource borrowed until the end of scope. Thus, when you `run_now` the `System`, it blows up because it needs write access to the `Bar` resource.

The solution is to explicitly scope the resource borrowing so the borrow is dropped before `run_now`:

```rust
{
    let mut bar = self.world.write_resource::<Bar>();
    *bar = Bar { baz: 43.0 };
}

let mut system = System;
system.run_now(&self.world);
```

Also, note that this particular issue is related to `specs` entirely. Coffee's architecture does not cause the issue.

**Comment by twe4ked** [comment]
Thanks for the extra info. I'm pretty new to Rust and I've never used an ECS so I was a bit lost for a while there. Coffee has been great so far!

**Comment by hecrj** [comment]
Glad to hear that! :heart: 

Feel free to open more issues! And let me know if I can help you with anything :)
